name: tests-payments

on:
  pull_request:
    path:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: cd payments npm install && npm run test:ci
