name: tests-tickets

on:
  pull_request:
    path:
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: cd tickets npm install && npm run test:ci
